DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Peliehdotus CASCADE;
DROP TABLE IF EXISTS Peliehdotus_Kayttaja CASCADE;
DROP TABLE IF EXISTS Kategoria CASCADE;
DROP TABLE IF EXISTS Peli CASCADE;
DROP TABLE IF EXISTS Arvostelu CASCADE;